# Generated by Django 5.1.3 on 2025-07-12 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата оплаты"
            ),
        ),
    ]
