# Generated by Django 5.1.3 on 2024-12-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="выберите курс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_set",
                to="lms.course",
                verbose_name="курс",
            ),
        ),
    ]
